version: '3.9'
services:
  app: 
    container_name: spring
    image: app-springboot-postgresql
    build: ./
    ports:
      - "8082:8080"
    depends_on:
      - db_postgresql

  db_postgresql:
      image: postgresql
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=Priya@777
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
