version: '3.9'
services:
  app: 
    container_name: spring
    build:
    ports:
      - "89:80"
    depends_on:
      - db_postgresql

  db_postgresql:
      image: postgresql
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=priya
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres